#!/usr/bin/env bash
#Installs and configure nginx to listen on port 80
#Respnds with "Hello World"

apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello Word!" > /var/www/html/index.html
service nginx restart
