#!/usr/bin/env bash
#Installs and configure nginx to listen on port 80
#Respnds with "Hello World"

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
service nginx start
