#!/usr/bin/env bash

# This script configures the container to run Nginx as the user
# nginx and listen on all active IPs on port 8080

sudo service nginx stop
sudo sed -i 's/user www-data/user nginx/g' etc/nginx/nginx.conf

sudo sed -i 's/listen 80 default_server/listen 8080 defalut_server/g' /etc/nginx/sites-available/default

sudo service nginx start
